export const data = [
    {
        'id': 1,
        'Name': 'Reactjs',
        'Introduction': 'ReactJS, also known as React, is a popular JavaScript library for building user interfaces. It is also referred to as a front-end JavaScript library. It was developed by Facebook and is widely used for creating dynamic and interactive web applications. React is a declarative, component based library that allows developers to build reusable UI components and It follows the Virtual DOM (Document Object Model) approach, which optimizes rendering performance by minimizing DOM updates. React is fast and works well with other tools and libraries.',
        'History': 'React was invented by Facebook developers who found the traditional DOM slow. By implementing a virtual DOM, React addressed this issue and gained popularity rapidly. The current stable version of ReactJS is 18.2.0, released on June 14, 2022. The library continues to evolve, introducing new features with each update.',
        'Features': ['React provides the feature to break down the UI into smaller, self-contained components. Each component can have its own state and props.','JSX is a syntax extension for JavaScript that allows developers to write HTML-like code within their JavaScript files. It makes React components more readable and expressive.','React maintains a lightweight representation of the actual DOM in memory. When changes occur, React efficiently updates only the necessary parts of the DOM.','One-way data binding, the name itself says that it is a one-direction flow. The data in react flows only in one direction i.e. the data is transferred from top to bottom i.e. from parent components to child components. The properties(props) in the child component cannot return the data to its parent component but it can have communication with the parent components to modify the states according to the provided inputs.','As we discussed earlier, react uses virtual DOM and updates only the modified parts. So , this makes the DOM to run faster. DOM executes in memory so we can create separate components which makes the DOM run faster.','React divides the web page into multiple components as it is component-based. Each component is a part of the UI design which has its own logic and design as shown in the below image. So the component logic which is written in JavaScript makes it easy and run faster and can be reusable.','React is recommended in creating SPAs, allowing smooth content updates without page reloads. Its focus on reusable components makes it ideal for real-time applications.'],
        'Prerequisite': ['For learning React first you have a clear understanding of HTML, CSS and JavaScript. As React is a JavaScript library and uses most of its concept so you really have to understands the major concepts of it.','HTML and CSS','JavaScript and ES6','JSX (Javascript XML) & Babel','Node+Npm','Git and CLI (Command Line Interface).'],
        'Resources': ['Official website of reactjs: https://react.dev/','geeksforgeeks: https://www.geeksforgeeks.org/react-tutorial/','w3schools: https://www.w3schools.com/react/','online platforms: Udemy, Coursera, FreeCodeCamp, etc.'],
        'Beginner level projects': ['Simple To-Do App', 'Weather App', 'Blog Platform'],
        'Intermediate level projects': ['E-commerce Platform', 'Real-Time Chat App', 'Social Media Dashboard'],
        'Adavance level projects': ['Advanced Analytics Dashboard', 'Large-Scale Enterprise App', 'Real-Time Data Visualization Tool'],
    },
    {
        'id': 2,
        'Name': 'Nodejs',
        'Introduction': 'Node.js is a powerful open-source, cross-platform JavaScript runtime environment that executes JavaScript code outside a web browser. It is used to build scalable network applications. Node.js uses an event-driven, non-blocking I/O model, making it lightweight and efficient.',
        'History': 'Node.js was created by Ryan Dahl in 2009, built on Google Chrome\'s V8 JavaScript engine. It has grown significantly since then, becoming one of the most popular platforms for building server-side applications.',
        'Features': ['Asynchronous and Event-Driven','Fast Execution','Single Programming Language','Cross-Platform Compatibility','Rich Ecosystem of Modules (npm)','Scalability','Strong Community Support'],
        'Resources': ['Official Node.js website: https://nodejs.org/','GeeksforGeeks: https://www.geeksforgeeks.org/nodejs/','w3schools: https://www.w3schools.com/nodejs/','Online platforms: Udemy, Coursera, FreeCodeCamp, etc.'],
        'Beginner level projects': ['Simple HTTP Server', 'Todo List App', 'Command Line Tool'],
        'Intermediate level projects': ['Chat Application', 'RESTful API', 'Real-time Collaboration Tool'],
        'Adavance level projects': ['E-commerce Platform', 'Microservices Architecture', 'Scalable Social Media App'],
    },
    {
        'id': 3,
        'Name': 'Django',
        'Introduction': 'Django is a high-level Python web framework that encourages rapid development and clean, pragmatic design. It was designed to help developers take applications from concept to completion as quickly as possible.',
        'History': 'Django was developed at the Lawrence Journal-World newspaper by Adrian Holovaty and Simon Willison in 2003. It was released publicly under a BSD license in July 2005, and has since become one of the most popular frameworks for web development.',
        'Features': ['Rapid Development','Secure','Scalable','Versatile','Fully Loaded','Open Source'],
        'Resources': ['Official Django website: https://www.djangoproject.com/','GeeksforGeeks: https://www.geeksforgeeks.org/django-tutorial/','w3schools: https://www.w3schools.com/django/','Online platforms: Udemy, Coursera, FreeCodeCamp, etc.'],
        'Beginner level projects': ['Personal Blog', 'Portfolio Website', 'Simple Poll App'],
        'Intermediate level projects': ['E-commerce Website', 'Blog Platform', 'News Aggregator'],
        'Adavance level projects': ['Social Networking Site', 'SaaS Application', 'Enterprise Management System'],
    },
    {
        'id': 4,
        'Name': 'Vuejs',
        'Introduction': 'Vue.js is a progressive JavaScript framework used for building user interfaces and single-page applications. It is designed to be incrementally adoptable, with a core library focusing on the view layer only.',
        'History': 'Vue.js was created by Evan You and first released in February 2014. Since then, it has rapidly grown in popularity, becoming a strong competitor to other frameworks like React and Angular.',
        'Features': ['Reactive Data Binding','Component-Based Architecture','Vue CLI','Virtual DOM','Transitions and Animations','Vue Router','Vuex for State Management'],
        'Resources': ['Official Vue.js website: https://vuejs.org/','GeeksforGeeks: https://www.geeksforgeeks.org/vue-js/','w3schools: https://www.w3schools.com/vuejs/','Online platforms: Udemy, Coursera, FreeCodeCamp, etc.'],
        'Beginner level projects': ['Simple To-Do App', 'Weather App', 'Calculator'],
        'Intermediate level projects': ['E-commerce Dashboard', 'Blog Platform', 'Chat Application'],
        'Adavance level projects': ['Project Management Tool', 'Real-Time Collaboration Tool', 'Advanced Analytics Dashboard'],
    },
    {
        'id': 5,
        'Name': 'Angular',
        'Introduction': 'Angular is a platform and framework for building single-page client applications using HTML and TypeScript. It is maintained by Google and a community of individuals and corporations.',
        'History': 'Angular (also referred to as "Angular 2+" or simply "Angular") was initially released in 2016 as a complete rewrite of AngularJS (Angular 1.x). The framework has seen several major updates and improvements since its inception.',
        'Features': ['Two-Way Data Binding','Dependency Injection','Directives','Component-Based Architecture','Reactive Programming with RxJS','Angular CLI','Built-in Testing'],
        'Resources': ['Official Angular website: https://angular.io/','GeeksforGeeks: https://www.geeksforgeeks.org/angular-tutorial/','w3schools: https://www.w3schools.com/angular/','Online platforms: Udemy, Coursera, FreeCodeCamp, etc.'],
        'Beginner level projects': ['Simple CRUD App', 'Weather Application', 'Task Tracker'],
        'Intermediate level projects': ['E-commerce Platform', 'Real-Time Chat Application', 'Content Management System'],
        'Adavance level projects': ['Enterprise Resource Planning (ERP) System', 'Real-Time Data Visualization Dashboard', 'Complex Workflow Management System'],
    },
    {
        'id': 6,
        'Name': 'Ruby on Rails',
        'Introduction': 'Ruby on Rails, or Rails, is a server-side web application framework written in Ruby under the MIT License. It is a model-view-controller (MVC) framework, providing default structures for a database, a web service, and web pages.',
        'History': 'Rails was created by David Heinemeier Hansson in 2003 and released as open-source in 2004. It has greatly influenced web development with its emphasis on convention over configuration and the use of the Ruby programming language.',
        'Features': ['Convention Over Configuration','MVC Architecture','RESTful Application Design','Active Record','Built-in Testing','Security Features','Scaffolding'],
        'Resources': ['Official Ruby on Rails website: https://rubyonrails.org/','GeeksforGeeks: https://www.geeksforgeeks.org/ruby-on-rails/','w3schools: https://www.w3schools.com/ruby/ruby_rails.asp','Online platforms: Udemy, Coursera, FreeCodeCamp, etc.'],
        'Beginner level projects': ['Simple Blog', 'Task Manager', 'Bookmarking App'],
        'Intermediate level projects': ['E-commerce Site', 'Event Management System', 'Social Media App'],
        'Adavance level projects': ['Project Management Software', 'SaaS Application', 'Large-Scale CMS'],
    },
    {
        'id': 7,
        'Name': 'Flask',
        'Introduction': 'Flask is a micro web framework written in Python. It is classified as a microframework because it does not require particular tools or libraries. It has no database abstraction layer, form validation, or any other components where pre-existing third-party libraries provide common functions.',
        'History': 'Flask was created by Armin Ronacher of Pocoo, an international group of Python enthusiasts. The first release was in April 2010. Flask\'s simplicity and flexibility have made it popular for smaller applications and APIs.',
        'Features': ['Lightweight','Modular','Built-in Development Server','RESTful Request Dispatching','Jinja2 Templating','Unit Testing Support','Extensible'],
        'Resources': ['Official Flask website: https://flask.palletsprojects.com/','GeeksforGeeks: https://www.geeksforgeeks.org/flask-python/','w3schools: https://www.w3schools.com/flask/','Online platforms: Udemy, Coursera, FreeCodeCamp, etc.'],
        'Beginner level projects': ['Hello World App', 'Simple Blog', 'RESTful API'],
        'Intermediate level projects': ['User Authentication System', 'File Upload App', 'Social Network'],
        'Adavance level projects': ['E-commerce Backend', 'Complex Dashboard', 'API Gateway'],
    },
    {
        'id': 8,
        'Name': 'Laravel',
        'Introduction': 'Laravel is a PHP framework for web artisans. It is a web application framework with expressive, elegant syntax. Laravel attempts to take the pain out of development by easing common tasks used in most web projects, such as authentication, routing, sessions, and caching.',
        'History': 'Laravel was created by Taylor Otwell in 2011 to provide a more advanced alternative to the CodeIgniter framework, which lacked certain features such as built-in user authentication.',
        'Features': ['Elegant Syntax','MVC Architecture','Eloquent ORM','Blade Templating','RESTful Controllers','Built-in Authentication','Task Scheduling'],
        'Resources': ['Official Laravel website: https://laravel.com/','GeeksforGeeks: https://www.geeksforgeeks.org/laravel/','w3schools: https://www.w3schools.com/laravel/','Online platforms: Udemy, Coursera, FreeCodeCamp, etc.'],
        'Beginner level projects': ['Simple Blog', 'Task Management App', 'Photo Gallery'],
        'Intermediate level projects': ['E-commerce Platform', 'API Backend', 'Event Management System'],
        'Adavance level projects': ['SaaS Application', 'Advanced CMS', 'Enterprise Solution'],
    },
    {
        'id': 9,
        'Name': 'Spring Boot',
        'Introduction': 'Spring Boot is an extension of the Spring framework that simplifies the initial setup of new Spring applications. It is a microservice-based framework that provides a platform for developing Java applications quickly.',
        'History': 'Spring Boot was introduced by the Pivotal team in 2014 to provide a simpler and faster way to set up, configure, and run both simple and web-based applications.',
        'Features': ['Auto-Configuration','Standalone Application','Spring CLI','Embedded Server','Production-Ready Features','Spring Initializr','Extensive Documentation'],
        'Resources': ['Official Spring Boot website: https://spring.io/projects/spring-boot','GeeksforGeeks: https://www.geeksforgeeks.org/spring-boot/','w3schools: https://www.w3schools.com/spring/','Online platforms: Udemy, Coursera, FreeCodeCamp, etc.'],
        'Beginner level projects': ['Simple REST API', 'CRUD Application', 'User Authentication System'],
        'Intermediate level projects': ['E-commerce Backend', 'Microservices Architecture', 'Content Management System'],
        'Adavance level projects': ['Enterprise Resource Planning System', 'Cloud-Native Applications', 'Complex Workflow Management'],
    },
    {
        'id': 10,
        'Name': 'Express.js',
        'Introduction': 'Express.js, or simply Express, is a minimal and flexible Node.js web application framework that provides a robust set of features for web and mobile applications.',
        'History': 'Express was created by TJ Holowaychuk and is maintained by the Node.js foundation and numerous open-source contributors. It has been widely adopted due to its simplicity and performance.',
        'Features': ['Minimalist Framework','Robust Routing','High Performance','Middleware Support','Flexible','Extensible','Supports REST APIs'],
        'Resources': ['Official Express.js website: https://expressjs.com/','GeeksforGeeks: https://www.geeksforgeeks.org/express-js/','w3schools: https://www.w3schools.com/express/','Online platforms: Udemy, Coursera, FreeCodeCamp, etc.'],
        'Beginner level projects': ['Simple Server', 'Todo List App', 'Weather Application'],
        'Intermediate level projects': ['Chat Application', 'E-commerce Backend', 'Blog Platform'],
        'Adavance level projects': ['Scalable REST API', 'Microservices Architecture', 'Real-Time Collaboration Tool'],
    },
    {
        'id': 11,
        'Name': 'ASP.NET Core',
        'Introduction': 'ASP.NET Core is a free, cross-platform, open-source framework for building modern, cloud-based, internet-connected applications. It is a redesign of ASP.NET, built on a modular framework that runs on both the full .NET Framework on Windows and the cross-platform .NET.',
        'History': 'ASP.NET Core was initially released in 2016 as a complete re-write of the existing ASP.NET framework. It was designed to be lean, modular, and fast, with cross-platform capabilities.',
        'Features': ['Cross-Platform','High Performance','Unified MVC & Web API Framework','Dependency Injection','Modular Components','Cloud-Ready','Comprehensive Documentation'],
        'Resources': ['Official ASP.NET Core website: https://dotnet.microsoft.com/apps/aspnet','GeeksforGeeks: https://www.geeksforgeeks.org/asp-net-core/','w3schools: https://www.w3schools.com/aspnet/core/','Online platforms: Udemy, Coursera, FreeCodeCamp, etc.'],
        'Beginner level projects': ['Simple Web App', 'CRUD Operations', 'User Authentication System'],
        'Intermediate level projects': ['E-commerce Platform', 'Blog Engine', 'Real-Time Notifications'],
        'Adavance level projects': ['Enterprise Web Applications', 'Microservices Architecture', 'Cloud-Based Solutions'],
    },
    {
        'id': 12,
        'Name': 'Svelte',
        'Introduction': 'Svelte is a radical new approach to building user interfaces. Whereas traditional frameworks like React and Vue do the bulk of their work in the browser, Svelte shifts that work into a compile step that happens when you build your app.',
        'History': 'Svelte was created by Rich Harris in 2016. It has gained popularity due to its innovative approach of compiling components into highly efficient imperative code that directly manipulates the DOM.',
        'Features': ['No Virtual DOM','Reactive Declarations','Built-In Transitions','Small Bundle Sizes','Write Less Code','Component-Based','Faster Performance'],
        'Resources': ['Official Svelte website: https://svelte.dev/','GeeksforGeeks: https://www.geeksforgeeks.org/svelte/','w3schools: https://www.w3schools.com/svelte/','Online platforms: Udemy, Coursera, FreeCodeCamp, etc.'],
        'Beginner level projects': ['Simple Counter App', 'Todo List', 'Weather App'],
        'Intermediate level projects': ['Blog Platform', 'Real-Time Chat Application', 'E-commerce Frontend'],
        'Adavance level projects': ['Complex Dashboard', 'Real-Time Collaboration Tool', 'Enterprise-Level Application'],
    },
    {
        'id': 13,
        'Name': 'Koa.js',
        'Introduction': 'Koa.js is a next-generation web framework for Node.js, designed by the team behind Express.js. It aims to be smaller, more expressive, and more robust, by leveraging async/await for better control over asynchronous code.',
        'History': 'Koa was created by the original developers of Express.js, aiming to provide a more refined and modern experience for building web applications and APIs. It was released in 2013.',
        'Features': ['Asynchronous by Default','Minimalist Framework','Robust Error Handling','Modular Components','No Middleware Included','Improved Code Maintainability','Built on ES6+'],
        'Resources': ['Official Koa.js website: https://koajs.com/','GeeksforGeeks: https://www.geeksforgeeks.org/koa-js/','w3schools: https://www.w3schools.com/koa/','Online platforms: Udemy, Coursera, FreeCodeCamp, etc.'],
        'Beginner level projects': ['Simple API Server', 'Todo List App', 'Basic Authentication'],
        'Intermediate level projects': ['RESTful API', 'Real-Time Chat Application', 'E-commerce Backend'],
        'Adavance level projects': ['Microservices Architecture', 'Complex Middleware System', 'Real-Time Data Processing'],
    },
    {
        'id': 14,
        'Name': 'NestJS',
        'Introduction': 'NestJS is a progressive Node.js framework for building efficient, reliable, and scalable server-side applications. It uses TypeScript as its primary language and combines elements of OOP, FP, and FRP.',
        'History': 'NestJS was created by Kamil Myśliwiec and was first released in 2017. It has since gained a strong community and is widely adopted for enterprise-grade applications.',
        'Features': ['TypeScript Support','Modular Architecture','Dependency Injection','Built-In Support for Microservices','Easy Testing','Extensible','Unified Backend Framework'],
        'Resources': ['Official NestJS website: https://nestjs.com/','GeeksforGeeks: https://www.geeksforgeeks.org/nestjs/','w3schools: https://www.w3schools.com/nestjs/','Online platforms: Udemy, Coursera, FreeCodeCamp, etc.'],
        'Beginner level projects': ['Simple CRUD Application', 'Todo List App', 'Basic REST API'],
        'Intermediate level projects': ['Chat Application', 'E-commerce Platform', 'Real-Time Data Processing'],
        'Adavance level projects': ['Microservices Architecture', 'Complex Backend System', 'Enterprise-Grade Application'],
    },
    {
        'id': 15,
        'Name': 'Meteor',
        'Introduction': 'Meteor is a full-stack JavaScript platform for developing modern web and mobile applications. It includes a key set of technologies for building connected-client reactive applications, a build tool, and a curated set of packages from the Node.js and general JavaScript community.',
        'History': 'Meteor was developed by Meteor Development Group and first released in 2012. It offers a comprehensive solution that integrates with MongoDB and is known for its ease of use and real-time capabilities.',
        'Features': ['Full-Stack Solution','Real-Time Data Updates','Isomorphic JavaScript','Built-In Authentication','Easy to Learn','Extensive Package Ecosystem','Mobile Integration'],
        'Resources': ['Official Meteor website: https://www.meteor.com/','GeeksforGeeks: https://www.geeksforgeeks.org/meteor/','w3schools: https://www.w3schools.com/meteor/','Online platforms: Udemy, Coursera, FreeCodeCamp, etc.'],
        'Beginner level projects': ['Simple Blog', 'Todo List App', 'Real-Time Chat'],
        'Intermediate level projects': ['E-commerce Platform', 'Social Media App', 'Project Management Tool'],
        'Adavance level projects': ['Enterprise-Level Application', 'Real-Time Collaboration Platform', 'Complex SaaS Solution'],
    },
    {
        'id': 16,
        'Name': 'Phoenix',
        'Introduction': 'Phoenix is a web development framework written in Elixir which implements the server-side Model View Controller (MVC) pattern. It is built on the Cowboy Erlang framework and the Elixir programming language, making it suitable for high-performance applications.',
        'History': 'Phoenix was created by Chris McCord in 2014. It is known for its real-time capabilities, scalability, and fault tolerance, taking full advantage of the BEAM virtual machine.',
        'Features': ['Real-Time Functionality','Fault Tolerant','Highly Scalable','LiveView','Channels','Ecto for Database Interactions','Built-In Testing'],
        'Resources': ['Official Phoenix website: https://www.phoenixframework.org/','GeeksforGeeks: https://www.geeksforgeeks.org/phoenix-framework/','w3schools: https://www.w3schools.com/phoenix/','Online platforms: Udemy, Coursera, FreeCodeCamp, etc.'],
        'Beginner level projects': ['Simple Blog', 'Chat Application', 'Todo List'],
        'Intermediate level projects': ['Real-Time Dashboard', 'E-commerce Site', 'Project Management Tool'],
        'Adavance level projects': ['High-Performance API', 'Complex Real-Time Systems', 'Enterprise-Level Applications'],
    },
    {
        'id': 17,
        'Name': 'Ember.js',
        'Introduction': 'Ember.js is an open-source JavaScript web framework, utilizing a component-service pattern. It allows developers to create scalable single-page web applications by incorporating the best practices into the framework.',
        'History': 'Ember.js was initially released in December 2011 by Yehuda Katz. It has since evolved into a mature framework with strong conventions and tooling.',
        'Features': ['Convention Over Configuration','Component-Service Architecture','Built-In Router','Ember CLI','Handlebars Templating','Ember Data','Strong Community Support'],
        'Resources': ['Official Ember.js website: https://emberjs.com/','GeeksforGeeks: https://www.geeksforgeeks.org/ember-js/','w3schools: https://www.w3schools.com/ember/','Online platforms: Udemy, Coursera, FreeCodeCamp, etc.'],
        'Beginner level projects': ['Simple Blog', 'Todo List App', 'User Authentication'],
        'Intermediate level projects': ['E-commerce Platform', 'Real-Time Chat App', 'Project Management Tool'],
        'Adavance level projects': ['Complex Dashboard', 'Enterprise Web Application', 'Real-Time Collaboration Tool'],
    },
    {
        'id': 18,
        'Name': 'Backbone.js',
        'Introduction': 'Backbone.js is a lightweight JavaScript library that adds structure to web applications by providing models with key-value binding and custom events, collections with a rich API of enumerable functions, views with declarative event handling, and connects it all to your existing API over a RESTful JSON interface.',
        'History': 'Backbone.js was created by Jeremy Ashkenas and released in 2010. It was one of the first JavaScript frameworks to introduce the MV* pattern, which has influenced many frameworks that followed.',
        'Features': ['MV* Pattern','RESTful JSON Interface','Event-Driven Communication','Lightweight','Extensible','Dependency on Underscore.js','Rich Ecosystem'],
        'Resources': ['Official Backbone.js website: http://backbonejs.org/','GeeksforGeeks: https://www.geeksforgeeks.org/backbone-js/','w3schools: https://www.w3schools.com/backbone/','Online platforms: Udemy, Coursera, FreeCodeCamp, etc.'],
        'Beginner level projects': ['Simple To-Do List', 'Basic Blog', 'Single Page App'],
        'Intermediate level projects': ['Task Management System', 'E-commerce Frontend', 'Real-Time Notifications'],
        'Adavance level projects': ['Complex SPA', 'Large Scale Application', 'Real-Time Collaboration Tool'],
    },
    {
        'id': 19,
        'Name': 'Symfony',
        'Introduction': 'Symfony is a set of reusable PHP components and a PHP framework for web projects. It is designed to speed up the creation and maintenance of web applications, replacing repetitive coding tasks.',
        'History': 'Symfony was created by Fabien Potencier in 2005. It has grown to become one of the most robust and flexible PHP frameworks available, with a large community and extensive documentation.',
        'Features': ['Reusable PHP Components','Modular Architecture','MVC Pattern','Built-In Debugging Tools','Security Features','Easy Testing','Rich Documentation'],
        'Resources': ['Official Symfony website: https://symfony.com/','GeeksforGeeks: https://www.geeksforgeeks.org/symfony/','w3schools: https://www.w3schools.com/symfony/','Online platforms: Udemy, Coursera, FreeCodeCamp, etc.'],
        'Beginner level projects': ['Simple Blog', 'Task Management App', 'Portfolio Website'],
        'Intermediate level projects': ['E-commerce Site', 'Content Management System', 'API Development'],
        'Adavance level projects': ['Complex Web Application', 'Enterprise-Grade Solutions', 'SaaS Application'],
    },
    {
        'id': 20,
        'Name': 'CodeIgniter',
        'Introduction': 'CodeIgniter is a powerful PHP framework with a very small footprint, built for developers who need a simple and elegant toolkit to create full-featured web applications.',
        'History': 'CodeIgniter was created by EllisLab and released in 2006. It is known for its speed and simplicity, making it a popular choice for developers who prefer a lean framework.',
        'Features': ['Small Footprint','High Performance','MVC Architecture','Form and Data Validation','Built-In Security Tools','Comprehensive Documentation','Flexible URI Routing'],
        'Resources': ['Official CodeIgniter website: https://codeigniter.com/','GeeksforGeeks: https://www.geeksforgeeks.org/codeigniter/','w3schools: https://www.w3schools.com/codeigniter/','Online platforms: Udemy, Coursera, FreeCodeCamp, etc.'],
        'Beginner level projects': ['Simple Blog', 'Todo List App', 'User Authentication'],
        'Intermediate level projects': ['E-commerce Site', 'Content Management System', 'API Development'],
        'Adavance level projects': ['Complex Web Application', 'Enterprise Solutions', 'SaaS Application'],
    },
    {
        'id': 21,
        'Name': 'Zend Framework',
        'Introduction': 'Zend Framework is an open-source, object-oriented web application framework for PHP 5. It has a flexible architecture that lets you build modern web applications and web services.',
        'History': 'Zend Framework was created by Zend Technologies and first released in 2006. It has evolved into a robust framework with a large user base and extensive components for various web development needs.',
        'Features': ['MVC Architecture','Reusable Components','Extensive Documentation','Built-In Security Features','Modular Approach','High Performance','Strong Community Support'],
        'Resources': ['Official Zend Framework website: https://framework.zend.com/','GeeksforGeeks: https://www.geeksforgeeks.org/zend-framework/','w3schools: https://www.w3schools.com/zend/','Online platforms: Udemy, Coursera, FreeCodeCamp, etc.'],
        'Beginner level projects': ['Simple Blog', 'Task Management App', 'Portfolio Website'],
        'Intermediate level projects': ['E-commerce Site', 'Content Management System', 'API Development'],
        'Adavance level projects': ['Complex Web Application', 'Enterprise Solutions', 'SaaS Application'],
    }
]
